site_name: SWD Project Documentation
site_url: https://projectswd12.github.io/SWD_Project/
use_directory_urls: true

theme:
  name: material

nav:
  - Home: README.md
  - Documentation:
      - Secrets Management: secrets-management.md
