name: Adaptability-Matrix

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_flutter:       
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Run unit tests
        run: flutter test

      - name: Build APK on Linux
        if: matrix.os == 'ubuntu-latest'
        run: flutter build apk --debug

      - name: Build desktop app on Windows
        if: matrix.os == 'windows-latest'
        run: flutter build windows --debug
