# .github/workflows/adaptability.yml
# Multi-OS workflow that builds & tests the Flutter project
# and *does not* fail on linter warnings / infos.

name: Adaptability-Matrix

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_flutter:               # ← job ID uses only letters/underscores
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      # Install Flutter SDK
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Static analysis (warnings/infos *won’t* break CI)
      - name: Run flutter analyze
        run: flutter analyze --no-fatal-warnings --no-fatal-infos

      # Unit tests (Dart/Flutter)
      - name: Run unit tests
        run: flutter test

      # Platform-specific build steps
      - name: Build APK on Linux
        if: matrix.os == 'ubuntu-latest'
        run: flutter build apk --debug

      - name: Build Windows desktop app
        if: matrix.os == 'windows-latest'
        run: flutter build windows --debug
