name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: tour_guide_manager

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          channel: stable
          cache: true

      - name: Check Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run unit tests with coverage
        run: flutter test --coverage

      - name: Show test coverage summary
        run: |
          sudo apt-get install lcov
          lcov --summary coverage/lcov.info

      - name: Run integration tests (optional)
        run: |
          set +e
          flutter test integration_test || true
